### ISSUE TITLE
REST issue: receive html upon fetch

### ISSUE THREAD

**Issue by Dawa12** [tech-scout/tech-scout#41]
We're currently receiving back an html response when doing a fetch call to our 'api/events' route.

Code snippet causing problems:
https://github.com/tech-scout/tech-scout/blob/master/src/ProfilePage/ProfilePage.jsx
line 23: AjaxAdapter.getAllEvents() 

![alt text](https://github.com/tech-scout/tech-scout/blob/master/screenshot_error.png?raw=true "error screenshot")

We believe the error message comes from the fact that the fetch response is an jsonified html document.

3 things we tried:
- using postman
- making a distinction in naming our api routes and app routes -- in case react-router was not playing nicely with our express router
- console.logging everywhere

**Comment by Dawa12** [comment]
@rapala61 @bobbyking @jasonseminara @irwin @Trevor

**Comment by jasonseminara** [comment]
@Dawa12 your problem is here https://github.com/tech-scout/tech-scout/blob/master/src/helpers/AjaxAdapter.js#L13 

you should 
`return r.json()` so it returns a promise from the `then`

**Comment by Dawa12** [comment]
Thanks @jasonseminara, we worked with Bobby further to resolve the issue. The issue was with our use of 'connect-history-api-fallback' library, which allows us to access a specific path directly via the address bar. However, though it worked well on front end, we realized it was interfering with our fetch calls and decided to move it to the bottom of the server file which ended up fixing our issue.

server file now looks like this:
```javascript
'use strict'
require('dotenv').config({ silent: true });
const express = require('express');
const logger  = require('morgan');
const path    = require('path');
const bodyParser = require('body-parser');

const app     = express();
const PORT    = process.argv[2] || process.env.port || 3000;


app.use(logger('dev'));

app.use(bodyParser.json());

app.get('/', (req, res) => res.redirect('/app'));
app.use('/api/events', require('./routes/events'));
app.use('/api/signup', require('./routes/signup'));

// using history api fallback library to access url paths directly
const history = require('connect-history-api-fallback');
app.use(history());
app.use(express.static(path.join(__dirname, 'dist')));

app.listen(PORT, () => console.log('server is up and running on port', PORT));

```
