### ISSUE TITLE
Cannot post to api. Receive typeError: Converting circular structure to JSON(…)

### ISSUE THREAD

**Issue by Dawa12** [tech-scout/tech-scout#49]
Note: please refer to the link below, to view my personal code (not the organization code). It may take us some time to merge my changes.
https://github.com/Dawa12/tech-scout/tree/eventlist

Be able to acurately describe your issue

Identify the code snippet that is giving you an issue
![alt text](https://github.com/Dawa12/tech-scout/blob/eventlist/error2.png?raw=true "Error message")

Tell us 3 things that you tried in order to solve the issue
- Searched google for error message but wasn't too helpful
- Used console logs
- Tested database model for adding a new event, since the npm watch says one of my properties doesn't exist. 

If there is an error message, tell us what that error message means
- So I believe that that JSON.stringify cannot execute if the parameter passed to it is not a 'circular structure'
Looks like there is more than one error:
![alt text](https://github.com/Dawa12/tech-scout/blob/eventlist/error%20message%203.png?raw=true "")

**Comment by Dawa12** [comment]
@jasonseminara @rapala61 @gittheking @irwintsay @trevorpreston

**Comment by trevorpreston** [comment]
Done.  Please close this when you get a minute.
